language: go

before_script:
  - go get github.com/golang/lint/golint
script:
  - go vet ./...                             # go vet is the official Go static analyzer
  - golint -set_exit_status $(go list ./...) # one last linter
  - go test ./...
