version: "3.2"

services:
  app:
    image: golang:1.13
    working_dir: /app
    volumes:
      - .:/app
      - .pkg:/go/pkgw
    ports:
      - "9999:9999"
    depends_on:
      - database
    command: ["go", "run", "main.go"]

  database:
    image: "postgres:10.6-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smog_entries
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db-data: {}