version: "3.2"

services:
  app:
    image: golang:1.11-alpine
    working_dir: /app
    volumes:
      - .:/app
      - .pkg:/go/pkg
    ports:
      - "9999:9999"
    command: ["go", "run", "main.go"]
